// backend/models/Notification.js
const mongoose = require("mongoose");

/**
 * 🛰️ TITAN NEURAL ALERT SYSTEM (v4.2)
 * Ref: Report Section 3.5 (Notification & Feedback Loop)
 * Purpose: Handling real-time academic updates and AI-driven Risk Alerts.
 */

const notificationSchema = new mongoose.Schema(
  {
    recipient: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },
    sender: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      default: null, // Null if generated by AI System
    },
    title: {
      type: String,
      required: true,
      trim: true,
      maxlength: 200,
    },
    message: {
      type: String,
      required: true,
      trim: true,
      maxlength: 2000,
    },
    // 🏷️ CATEGORY: Refined for UI icon logic and Prediction Alerts
    type: {
      type: String,
      enum: ["ASSIGNMENT", "GRADE", "ATTENDANCE", "ANNOUNCEMENT", "RISK", "SYSTEM"],
      default: "SYSTEM"
    },
    // 🚦 PRIORITY: To drive 'Ringing' intensity (High priority = Red Alert)
    priority: {
      type: String,
      enum: ["low", "medium", "high"],
      default: "low"
    },
    // 🎯 REDIRECT_NODE: For frontend navigation (e.g., /dashboard/analytics)
    link: {
      type: String,
      default: null
    },
    isRead: {
      type: Boolean,
      default: false,
      index: true,
    },
  },
  { 
    timestamps: true 
  }
);

/**
 * 🚀 TELEMETRY INDEXING
 * Optimized for high-speed retrieval of unread alerts for specific user nodes.
 */
notificationSchema.index({ recipient: 1, isRead: 1, createdAt: -1 });

module.exports = mongoose.model("Notification", notificationSchema);